### ISSUE TITLE
Change repository type to private?

### ISSUE THREAD

**Issue by allsey87** [iridia-ulb/references#12]
Is there any reason why this repository is public?

**Comment by MLopez-Ibanez** [comment]
It is for the general public. In fact, apart from Thomas, Alberto and myself, I'm not sure anyone in IRIDIA is using it any more (I would be happy if they were using it since we put a lot of effort to document it and automatize it but alas, people seem to prefer the latest fad like Mendely or whatever is cool nowadays but fail at citing properly their own co-workers...)
