### ISSUE TITLE
Splitting biblio.bib

### ISSUE THREAD

**Issue by MLopez-Ibanez** [iridia-ulb/references#9]
biblio.bib is close to reaching 1MB. This may be an issue for some editors (not for emacs!).

One solution would be to split it by clear-cut topics. Some suggestions:

* ACO: It should be easy to decide if a work is connected to ACO or not. Since we have many ACO entries, this will significantly reduce the size.
* Multi-objective: There are a lot of works related to multiple objectives. We would need to decide whether to include MCDM, since there is a lot of overlap.
* GECCO: Another option is to put all GECCO entries on its own file, since we have quite a bit.

Other suggestions?

Orthogonal to the above is to make more use of strings in authors.bib, crossref.bib and abbrev.bib. This will reduce the size of biblio.bib but just slightly.

**Comment by albertofranzin** [comment]
Of the three options you listed, the third one is definitely the one I prefer, as it is by far the most objective. It is easy to know if a paper is in GECCO, CEC, etc, and most importantly it's unambiguous. Alternatively, I'd prefer to split the file by the first letter of the key or title. The other criteria introduce some subjectivity that needs to be disambiguated with some priority criteria to define. For example, how should MOACO be classified, under ACO or multiobjective? It's not impossible to solve, but it just makes it more cumbersome and not worthwhile, imho.

That said, personally I think the problem is not in the file size per se, but rather in the length of the file, which makes it more time consuming to move around if you (well, I) don't know exactly what you're looking for. BTW, this would worsen when splitting the file, so for now I'd still keep everything into one single file. Maybe using some anchor strings, such as "%#SecA", "%#SecB" to delimit sections whose entries start by A, B, etc would make more ctrl+f friendly (for me, at least), but I don't know how much anyone else would use that. Without that, for now I'd keep it as it is now.

**Comment by MLopez-Ibanez** [comment]
I have split `biblio.bib` into `articles.bib`. This split turned out to be very fair because both resulting files are almost the same size. So this should be fixed for a while.
